<%--<%@ Page Language="C#" AutoEventWireup="true" CodeFile="hccgroup1.aspx.cs" Inherits="hccgroup1" %>--%>
<%@ Page Title="" Language="C#" MasterPageFile="~/inner.master" AutoEventWireup="true"
    CodeFile="whitepapers.aspx.cs" Inherits="whitepapers" %>


<asp:Content ID="Content1" ContentPlaceHolderID="HeadContent" runat="Server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="MainContent" runat="Server">
    <link href="<%=ReturnUrl("css") %>profile/mprofile.css" rel="stylesheet" type="text/css" />
   
           <div class="userposts"><span>Whitepapers</span> </div>
                <div class="mainpostwallcat">
                     <div class="comments-summery1"> 
                     <span>
                        <a id="gobackbtn" href='<%=ReturnUrl("KnowledgeCentonHome")%>' class="aaa" > Knowledge Center </a>
                    </span>
                     </div>
              </div>
             
 <div class="projectmenu1"> 
            <ul>
                <li><a href="#" class="whitepaperheadertitle">Topics </a><a href="#" class="whitepaperheaderauthor">Author</a><a href="#" class="whitepaperheaderyear">Year </a><%--<i class="fa fa-plus" aria-hidden="true">
                </i></li>--%>
<li><a href="files\Articles_Whitepapers\2019_Safety in construction of underground structures in complex geology of Tehri Pump Storage Project.pdf" class="whitepapertitle"> Safety during construction of Tehri Pump Storage Project </a><a href="#" class="whitepaperauthor"> R.K. Khali </a><a href="#" class="whitepaperyear">2019</a><%--<i class="fa fa-plus" aria-hidden="true"> </li>--%>
<li><a href="files\Articles_Whitepapers\2018_DBM to launch TBMS_Jitendra Thakur and Jatinder Bali.pdf" class="whitepapertitle"> DBM to launch TBM's </a><a href="#" class="whitepaperauthor"> Jintendra Thakur & Jatinder Bali </a><a href="#" class="whitepaperyear">2018 </a><%--<i class="fa fa-plus" aria-hidden="true"> </li>--%>
<li><a href="files\Articles_Whitepapers\2018_ Construction of Railway Tunnel T-49 in Highly Adverse Geological Conditions _ Mr. Rakeshkumar Khali.pdf#toolbar=0&navpanes=0&pagemode=none" class="whitepapertitle"> Construction of Railway Tunnel T- 49 in the Himalayas using NATM </a><a href="#" class="whitepaperauthor"> Rakesh Kumar Khali </a><a href="#" class="whitepaperyear">2018 </a><%--<i class="fa fa-plus" aria-hidden="true"> </li>--%>
<li><a href="files\Articles_Whitepapers\2017_Surge Shaft Excavation & Concrete_Basavraj and SD Jeur.pdf" class="whitepapertitle"> Surge Shaft Excavation and Concrete Lining with Slipform at Punatsangchhu- 1 HEP </a><a href="#" class="whitepaperauthor"> Basavraj Kumbhar & S D Jeur </a><a href="#" class="whitepaperyear">2017 </a><%--<i class="fa fa-plus" aria-hidden="true"> </li>--%>
<li><a href="files\Articles_Whitepapers\Making of Padur Cavern Porject.pdf" class="whitepapertitle"> Making of Padur Cavern Project </a><a href="#" class="whitepaperauthor"> Corporate Communications </a><a href="#" class="whitepaperyear">2015 </a><%--<i class="fa fa-plus" aria-hidden="true"> </li>--%>
<li><a href="files\Articles_Whitepapers\Making of Nimoo Bazgo HEP.pdf" class="whitepapertitle"> Making of Nimoo Bazgo HEP </a><a href="#" class="whitepaperauthor"> Corporate Communications </a><a href="#" class="whitepaperyear">2015 </a><%--<i class="fa fa-plus" aria-hidden="true"> </li>--%>
<li><a href="files\Articles_Whitepapers\Making of Maroshi Ruparel Water Pipeline Tunnel Project.pdf" class="whitepapertitle"> Making of Maroshi Ruparel Water Pipeline Tunnel Project </a><a href="#" class="whitepaperauthor"> Corporate Communications </a><a href="#" class="whitepaperyear">2015 </a><%--<i class="fa fa-plus" aria-hidden="true"> </li>--%>
<li><a href="files\Articles_Whitepapers\Making of Chutak HEP.pdf" class="whitepapertitle"> Making of Chutak HEP </a><a href="#" class="whitepaperauthor"> Corporate Communications </a><a href="#" class="whitepaperyear">2015 </a><%--<i class="fa fa-plus" aria-hidden="true"> </li>--%>
<li><a href="files\Articles_Whitepapers\2015_Single stage concrete pumping through 2.432 km_Weather and execution challenges_Case Studies in Constr Mat.pdf" class="whitepapertitle"> Sainj HEP - Single stage concrete pumping through 2.432 km </a><a href="#" class="whitepaperauthor"> Chetan Hazare </a><a href="#" class="whitepaperyear">2015 </a><%--<i class="fa fa-plus" aria-hidden="true"> </li>--%>
<li><a href="files\Articles_Whitepapers\2015_Making of Kudankulam Nuclear Power Plant.pdf" class="whitepapertitle"> Making of Kudankulam Nuclear Power Plant </a><a href="#" class="whitepaperauthor"> Corporate Communications </a><a href="#" class="whitepaperyear">2015 </a><%--<i class="fa fa-plus" aria-hidden="true"> </li>--%>
<li><a href="files\Articles_Whitepapers\2015_Essential Practical aspects of pumping concrete thr a world-record distance of 2.432 km_CE and CR.pdf" class="whitepapertitle"> Essential Practical aspects of pumping concrete through a world-record distance of 2.432 km </a><a href="#" class="whitepaperauthor"> Chetan Hazaree </a><a href="#" class="whitepaperyear">2015 </a><%--<i class="fa fa-plus" aria-hidden="true"> </li>--%>
<li><a href="files\Articles_Whitepapers\2015_Are Specifications Impeding Sustainability of Concrete_ICJ.pdf" class="whitepapertitle"> Are Specifications Impeding Sustainability of Concrete-ICJ </a><a href="#" class="whitepaperauthor"> Chetan Hazaree & SM Vaidya </a><a href="#" class="whitepaperyear">2015 </a><%--<i class="fa fa-plus" aria-hidden="true"> </li>--%>
<li><a href="files\Articles_Whitepapers\Construction of surge Shaft by Slip form for Kishanganga HEP.pdf" class="whitepapertitle"> Construction of surge Shaft by Slip form for Kishanganga HEP </a><a href="#" class="whitepaperauthor"> Highbar </a><a href="#" class="whitepaperyear">2014 </a><%--<i class="fa fa-plus" aria-hidden="true"> </li>--%>
<li><a href="files\Articles_Whitepapers\2014_Pumping concrete through a record distance of 2.432 km_Masterbuilder.pdf" class="whitepapertitle"> Sainj HEP - Pumping concrete through a record distance of 2.432 km </a><a href="#" class="whitepaperauthor"> Chetan Hazaree </a><a href="#" class="whitepaperyear">2015 </a><%--<i class="fa fa-plus" aria-hidden="true"> </li>--%>
<li><a href="files\Articles_Whitepapers\2014_Pia Panjal Rail Tunnel - The Longest Transportation Tunnel in India.pdf" class="whitepapertitle"> Pir Panjal Rail Tunnel - The Longest Transportation Tunnel in India </a><a href="#" class="whitepaperauthor"> Corporate Communications </a><a href="#" class="whitepaperyear">2014 </a><%--<i class="fa fa-plus" aria-hidden="true"> </li>--%>
<li><a href="files\Articles_Whitepapers\2012_Making of Badarpur flyover elevated highway.pdf" class="whitepapertitle"> Making of Badarpur flyover elevated highway </a><a href="#" class="whitepaperauthor"> Corporate Communications </a><a href="#" class="whitepaperyear">2012 </a><%--<i class="fa fa-plus" aria-hidden="true"> </li>--%>
<li><a href="files\Articles_Whitepapers\2011_Something Concrete_Construction World.pdf" class="whitepapertitle"> Something Concrete - Construction World </a><a href="#" class="whitepaperauthor"> Chetan Hazaree </a><a href="#" class="whitepaperyear">2011 </a><%--<i class="fa fa-plus" aria-hidden="true"> </li>--%>
<li><a href="files\Articles_Whitepapers\2011_Method of Excavaion of underground rock caverns for storage of crude oil at Visakhapatnam - a case study.pdf" class="whitepapertitle"> Method of Excavaion of underground rock caverns for storage of crude oil at Visakhapatnam - a case study </a><a href="#" class="whitepaperauthor"> Chetan Hazaree </a><a href="#" class="whitepaperyear">2011 </a><%--<i class="fa fa-plus" aria-hidden="true"> </li>--%>
<li><a href="files\Articles_Whitepapers\2011_Influences of mixture composition on properties and freeze–thaw resistance of RCC_Constr and Bldg Mat.pdf" class="whitepapertitle"> Influences of mixture composition on properties</a><a href="#" class="whitepaperauthor"> Chetan Hazaree </a><a href="#" class="whitepaperyear">2011 </a><%--<i class="fa fa-plus" aria-hidden="true"> </li>--%>
<li><a href="files\Articles_Whitepapers\2011_Capillary Transport in RCC_Water-to-Cement Ratio, Strength, and Freeze-Thaw Resistance _ASCEJoMCE.pdf" class="whitepapertitle"> Capillary Transport in RCC</a><a href="#" class="whitepaperauthor"> Chetan Hazaree </a><a href="#" class="whitepaperyear">2011 </a><%--<i class="fa fa-plus" aria-hidden="true"> </li>--%>
<li><a href="files\Articles_Whitepapers\2010_Making of Pir Panjal Rail Tunnel.pdf" class="whitepapertitle"> Making of Pir Panjal Rail Tunnel Project </a><a href="#" class="whitepaperauthor"> Corporate Communications </a><a href="#" class="whitepaperyear">2010 </a><%--<i class="fa fa-plus" aria-hidden="true"> </li>--%>
<li><a href="files\Articles_Whitepapers\2009_Ennore Port case study.pdf" class="whitepapertitle"> Ennore Port case study </a><a href="#" class="whitepaperauthor"> Jagman Singh </a><a href="#" class="whitepaperyear">2009 </a><%--<i class="fa fa-plus" aria-hidden="true"> </li>--%>
<li><a href="files\Articles_Whitepapers\2008_Making of Mughal Road Project.pdf" class="whitepapertitle"> Making of Mughal Road Project </a><a href="#" class="whitepaperauthor"> Corporate Communications </a><a href="#" class="whitepaperyear">2008 </a><%--<i class="fa fa-plus" aria-hidden="true"> </li>--%>
<li><a href="files\Articles_Whitepapers\2007_THE SINKING OF WELL FOUNDATIONS IN DIFFICULT SITUATIONS.pdf" class="whitepapertitle"> The Sinking of Well Foundations in difficult situations </a><a href="#" class="whitepaperauthor"> GP Saha </a><a href="#" class="whitepaperyear">2007 </a><%--<i class="fa fa-plus" aria-hidden="true"> </li>--%>
<li><a href="files\Articles_Whitepapers\2007_Making of Bandra Worli Sea Link.pdf" class="whitepapertitle"> Making of Bandra Worli Sea Link Project </a><a href="#" class="whitepaperauthor"> Corporate Communications </a><a href="#" class="whitepaperyear">2007 </a><%--<i class="fa fa-plus" aria-hidden="true"> </li>--%>
<li><a href="files\Articles_Whitepapers\2006_Ecofriendly Concrete with High Volume of Lagoon Ash.pdf" class="whitepapertitle"> Ecofriendly Concrete with High Volume of Lagoon Ash </a><a href="#" class="whitepaperauthor"> Chetan Hazaree </a><a href="#" class="whitepaperyear">2006 </a><%--<i class="fa fa-plus" aria-hidden="true"> </li>--%>
<li><a href="files\Articles_Whitepapers\2006_Concrete Mixtures with High Microfines.pdf" class="whitepapertitle"> Concrete Mixtures with High Microfines </a><a href="#" class="whitepaperauthor"> Chetan Hazaree </a><a href="#" class="whitepaperyear">2006 </a><%--<i class="fa fa-plus" aria-hidden="true"> </li>--%>
<li><a href="files\Articles_Whitepapers\2005_A handbook of construction plants and equipments.pdf" class="whitepapertitle"> A handbook of construction plants and equipments </a><a href="#" class="whitepaperauthor"> Bhave & Allen </a><a href="#" class="whitepaperyear">2005 </a><%--<i class="fa fa-plus" aria-hidden="true"> </li>--%>
<li><a href="files\Articles_Whitepapers\2004_Towards better concrete.pdf" class="whitepapertitle"> Towards Better Concrete </a><a href="#" class="whitepaperauthor"> Highbar </a><a href="#" class="whitepaperyear">2004 </a><%--<i class="fa fa-plus" aria-hidden="true"> </li>--%>
<li><a href="files\Articles_Whitepapers\2004_Concrete inspection manual.pdf" class="whitepapertitle"> Concrete Inspection Manual </a><a href="#" class="whitepaperauthor"> Highbar </a><a href="#" class="whitepaperyear">2004 </a><%--<i class="fa fa-plus" aria-hidden="true"> </li>--%>
<li><a href="files\Articles_Whitepapers\2003_Designing A Crushing Plant.pdf" class="whitepapertitle"> Designing a Crushing Plant </a><a href="#" class="whitepaperauthor"> RV Datey </a><a href="#" class="whitepaperyear">2003 </a><%--<i class="fa fa-plus" aria-hidden="true"> </li>--%>
<li><a href="files\Articles_Whitepapers\2002_Introduction to Environmental Management System.pdf" class="whitepapertitle"> Introduction to Environmental Management System </a><a href="#" class="whitepaperauthor"> Highbar </a><a href="#" class="whitepaperyear">2002 </a><%--<i class="fa fa-plus" aria-hidden="true"> </li>--%>
<li><a href="files\Articles_Whitepapers\2002_Environmental Guide towards Sustainable Construction.pdf" class="whitepapertitle"> Environmental Guide towards Sustainable Construction </a><a href="#" class="whitepaperauthor"> Highbar </a><a href="#" class="whitepaperyear">2002 </a><%--<i class="fa fa-plus" aria-hidden="true"> </li>--%>
<li><a href="files\Articles_Whitepapers\2001_Longest Breakwater in India.pdf" class="whitepapertitle"> Ennore Breakwaters - Longest Breakwater in India </a><a href="#" class="whitepaperauthor"> MD Khattar </a><a href="#" class="whitepaperyear">2001 </a><%--<i class="fa fa-plus" aria-hidden="true"> </li>--%>
<li><a href="files\Articles_Whitepapers\2000_Ennore C-1 Project Karikkal Quarry - Part 5.pdf" class="whitepapertitle"> Ennore C-1 Project Karikkal Quarry-Part 5 </a><a href="#" class="whitepaperauthor"> Highbar </a><a href="#" class="whitepaperyear">2000 </a><%--<i class="fa fa-plus" aria-hidden="true"> </li>--%>
<li><a href="files\Articles_Whitepapers\2000_Ennore C-1 Project Karikkal Quarry - Part 4.pdf" class="whitepapertitle"> Ennore C-1 Project Karikkal Quarry-Part 4 </a><a href="#" class="whitepaperauthor"> Highbar </a><a href="#" class="whitepaperyear">2000 </a><%--<i class="fa fa-plus" aria-hidden="true"> </li>--%>
<li><a href="files\Articles_Whitepapers\2000_Ennore C-1 Project Karikkal Quarry - Part 3.pdf" class="whitepapertitle"> Ennore C-1 Project Karikkal Quarry-Part 3 </a><a href="#" class="whitepaperauthor"> Highbar </a><a href="#" class="whitepaperyear">2000 </a><%--<i class="fa fa-plus" aria-hidden="true"> </li>--%>
<li><a href="files\Articles_Whitepapers\2000_Ennore C-1 Project Karikkal Quarry - Part 2.pdf" class="whitepapertitle"> Ennore C-1 Project Karikkal Quarry-Part 2 </a><a href="#" class="whitepaperauthor"> Highbar </a><a href="#" class="whitepaperyear">2000 </a><%--<i class="fa fa-plus" aria-hidden="true"> </li>--%>
<li><a href="files\Articles_Whitepapers\2000_Ennore Breakwater Construction.pdf" class="whitepapertitle"> Ennore Breakwater Construction </a><a href="#" class="whitepaperauthor"> Highbar </a><a href="#" class="whitepaperyear">2000 </a><%--<i class="fa fa-plus" aria-hidden="true"> </li>--%>
<li><a href="files\Articles_Whitepapers\1995-new metro works kolkatta.pdf" class="whitepapertitle"> New Metro Works Kolkatta </a><a href="#" class="whitepaperauthor"> Highbar </a><a href="#" class="whitepaperyear">1995 </a><%--<i class="fa fa-plus" aria-hidden="true"> </li>--%>
<li><a href="files\Articles_Whitepapers\1995_Construction of power tunnel and power house for Chamera HEP.pdf" class="whitepapertitle"> Construction of power tunnel and power house for Chamera HEP </a><a href="#" class="whitepaperauthor"> SK Dharmadhikari </a><a href="#" class="whitepaperyear">1995 </a><%--<i class="fa fa-plus" aria-hidden="true"> </li>--%>
<li><a href="files\Articles_Whitepapers\1992-Foundations for deep scour_ Ganga bridge at Varanasi.pdf" class="whitepapertitle"> Foundations for deep scour - Ganga bridge at Varanasi </a><a href="#" class="whitepaperauthor"> GP Saha </a><a href="#" class="whitepaperyear">1992 </a><%--<i class="fa fa-plus" aria-hidden="true"> </li>--%>
<li><a href="files\Articles_Whitepapers\1983-Reactor Building for Narora Atomic Power Project (India).pdf" class="whitepapertitle"> Reactor Building for Narora Atomic Power Project (India) </a><a href="#" class="whitepaperauthor"> NN Kulkarni & JS Goray </a><a href="#" class="whitepaperyear">1983 </a><%--<i class="fa fa-plus" aria-hidden="true"> </li>--%>
<li><a href="files\Articles_Whitepapers\1968_Completion Report on Farakka Barrage Complex.pdf" class="whitepapertitle"> Completion Report on Farakka Barrage Complex </a><a href="#" class="whitepaperauthor"> Highbar </a><a href="#" class="whitepaperyear">1968 </a><%--<i class="fa fa-plus" aria-hidden="true"> </li>--%>
				
				<!-- Add New article code above -->	
				
            </ul>
        </div>

</asp:Content>

